// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGmzLnquhb4MCXW4hEIooh1gdgd8W0Djc',
    appId: '1:958991568380:web:98c0ba331dc3d6ebd23679',
    messagingSenderId: '958991568380',
    projectId: 'parkinglot-3857b',
    authDomain: 'parkinglot-3857b.firebaseapp.com',
    storageBucket: 'parkinglot-3857b.firebasestorage.app',
    measurementId: 'G-JC949ZVBM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQbaAMG4Jd-ZAmZj-M02Gul1cDgeDb6Q',
    appId: '1:958991568380:android:1058a13591100937d23679',
    messagingSenderId: '958991568380',
    projectId: 'parkinglot-3857b',
    storageBucket: 'parkinglot-3857b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-yWsqaYpqx_3kc_Fbt4IEnOZxzj1vY6Y',
    appId: '1:958991568380:ios:13caf5b7621844e2d23679',
    messagingSenderId: '958991568380',
    projectId: 'parkinglot-3857b',
    storageBucket: 'parkinglot-3857b.firebasestorage.app',
    iosClientId: '958991568380-2qchq35ec0d050vkdt1ik7hau14ubfpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkinglot.parkinglot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-yWsqaYpqx_3kc_Fbt4IEnOZxzj1vY6Y',
    appId: '1:958991568380:ios:13caf5b7621844e2d23679',
    messagingSenderId: '958991568380',
    projectId: 'parkinglot-3857b',
    storageBucket: 'parkinglot-3857b.firebasestorage.app',
    iosClientId: '958991568380-2qchq35ec0d050vkdt1ik7hau14ubfpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkinglot.parkinglot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGmzLnquhb4MCXW4hEIooh1gdgd8W0Djc',
    appId: '1:958991568380:web:f8b26bbe9c9dba99d23679',
    messagingSenderId: '958991568380',
    projectId: 'parkinglot-3857b',
    authDomain: 'parkinglot-3857b.firebaseapp.com',
    storageBucket: 'parkinglot-3857b.firebasestorage.app',
    measurementId: 'G-FZXXBXQ9EZ',
  );
}
